### PR TITLE
Use catkin tools to run unit tests

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by HannesSommer** [comment]
This should settle #83.

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
retest this please

**Comment by helenol** [comment]
LGTM :)

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
Okay, let's be bold and merge :).

**Pull request merged**
