### PR TITLE
Added public artifact test

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
@ffurrer  : Finally, it works! 
This is an example from continuous_integration:
DEPLOY:
public-artifacts

Remote file location (copy me): 
```
/var/www/public_artifacts/${JOB_NAME}/${BUILD_NUMBER}/
```

BUILD MESSAGE:
trigger-setup-using-public-artifacts

Example image link for message (copy me): 
```continuous_integration
![YOUR_TITLE](http://129.132.38.183:8000/public_artifacts/${JOB_NAME}/${BUILD_NUMBER}/YOURIMAGE.jpg)
```

**Comment by ffurrer** [comment]
@HannesSommer Awesome, thanks a lot :)

**Pull request merged**
