### PR TITLE
Fixed the cmake-args flag formatting

### PR DESCRIPTION
**Pull request by dymczykm**
@uschwes

### CODE REVIEW

**Comment by HannesSommer** [comment]
Thanks, @dymczykm . Just out of curiosity: Where does the version you fixed cause problems? IMO it should be equivalent. Is there a catkin tools version that doesn't support the other way?

**Comment by dymczykm** [comment]
gtsam:
```
[gtsam] ==> '/home/jenkins/workspace/subtree_multiagent_mapping/build/gtsam/build_env.sh /usr/bin/cmake /home/jenkins/workspace/subtree_multiagent_mapping/src/gtsam_devel -DCMAKE_INSTALL_PREFIX=/home/jenkins/workspace/subtree_multiagent_mapping/devel -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-DALWAYS_ASSERT -DCMAKE_C_FLAGS=-DALWAYS_ASSERT' in '/home/jenkins/workspace/subtree_multiagent_mapping/build/gtsam' -- The CXX compiler identification is GNU 4.8.4 -- The C compiler identification is GNU 4.8.4 -- Check for working CXX compiler: /usr/lib/ccache/g++ -- Check for working CXX compiler: /usr/lib/ccache/g++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working C compiler: /usr/lib/ccache/gcc -- Check for working C compiler: /usr/lib/ccache/gcc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- GTSAM_SOURCE_ROOT_DIR: 
[/home/jenkins/workspace/subtree_multiagent_mapping/src/gtsam_devel] CMake Error at cmake/GtsamBuildTypes.cmake:103 (message): Unknown build type "Release -DCMAKE_CXX_FLAGS=-DALWAYS_ASSERT -DCMAKE_C_FLAGS=-DALWAYS_ASSERT". Allowed values are None, Debug, Release, Timing, Profiling, RelWithDebInfo (case-insensitive). Call Stack (most recent call first): CMakeLists.txt:32 (include) -- 

Configuring incomplete, errors occurred! See also "/home/jenkins/workspace/subtree_multiagent_mapping/build/gtsam/CMakeFiles/CMakeOutput.log". [gtsam] 
<== '/home/jenkins/workspace/subtree_multiagent_mapping/build/gtsam/build_env.sh /usr/bin/cmake /home/jenkins/workspace/subtree_multiagent_mapping/src/gtsam_devel -DCMAKE_INSTALL_PREFIX=/home/jenkins/workspace/subtree_multiagent_mapping/devel -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-DALWAYS_ASSERT -DCMAKE_C_FLAGS=-DALWAYS_ASSERT' failed with return code '1' Failed 
<== gtsam [ 0.5 seconds ]
```

does it lgty?

**Comment by HannesSommer** [comment]
Ah, thanks. So it makes a difference, because it isn't split anymore. Learned something :). I trusted in the unit tests within this package but it wasn't good enough apparently because plain cmake doesn't complain about wired build type names.

Yes, lgtm and sorry for the delay.

**Comment by dymczykm** [comment]
@HannesSommer thanks for merging! Yes, it seems that parsing the vars to get the CMAKE_BUILD_TYPE is not handling such cases well.

**Pull request merged**
