### PR TITLE
More aggressive wstool and http for catkin_simple

### PR DESCRIPTION
**Pull request by HannesSommer**
Instruct wstool to forcefully replace with merge and update to get the newest version even when the workspace wasn't wiped.

### CODE REVIEW

**Comment by HannesSommer** [comment]
retest this please

**Comment by schneith** [comment]
lgtm

**Comment by HannesSommer** [comment]
thanks for taking a look @schneith .

**Comment by rdube** [comment]
I'm sure it's good! :)

**Pull request merged**
