### PR TITLE
Treat https and ssh github URIs as equal

### PR DESCRIPTION
**Pull request by HannesSommer**
@ffurrer , @ntonci , this is my solution to https://github.com/ethz-asl/minkindr/pull/62. 
Sorry for the potentially duplicated work.

### CODE REVIEW

**Comment by ffurrer** [comment]
no worries, this is maybe a bit cleaner ;). In my version I had the intent to being able to select whether one wants ssh or https entries, but then noted later that this doesn't work that easily, as you take the output from the terminal and old entries are already parsed ;). So feel free to use this :).

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
Yes, it is the more feasible solution. However, how do we get your nice cleanup in? Maybe you can convert your PR into a cleanup PR?

**Comment by HannesSommer** [comment]
Self LGTM.

**Pull request merged**
