### PR TITLE
New flag: {-x|--prepare-system-script} run this script between cloning and building

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
retest this please

**Comment by HannesSommer** [comment]
@helenol , what do you think about this solution? 
Yes, Jenkins is / would need to be allowed to run `sudo apt-get install SOMETHING`
@schneith , @eggerk, @mbuerki , any objections / remarks?

**Comment by helenol** [comment]
Looks great, Hannes! We should just be a little careful with the scripts to make sure no one pulls an `rm -rf *` ;)
I guess an alternative would be to just get a list of packages to apt-get install, which is probably a little safer, but this is definitely more flexible for random setup crap that needs to be done.

**Comment by HannesSommer** [comment]
@helenol , good point. I also thought about that. What finally convinced me was the thought that right now every unit test could do that `rm -rf *`!
To gain any reasonable level of safety we would have to invest much more. And given this current level of safety we might as well benefit from the extra comfort, simplicity and flexibility ;).
For instance a list of packages to install would get quite complicated if one needs to support different platforms. This difficulty is now pushed down to the responsibility of these scripts. And therefore for packages that don't needed to run on different platforms things remain easy.

**Comment by helenol** [comment]
Yes, that's definitely true -- since we need to do these same scripts on the mac slaves... Yes, I completely agree now -- shell script is the way to go.

**Comment by HannesSommer** [comment]
Okay, I'm merging this because it won't anybody as long as it isn't used. We can remove it later if late objects come in.
I just hope the also introduced argument validation is not going to break too much. But this is something important to have IMO.

**Pull request merged**
